### ISSUE TITLE
Seeking information about simulation of P and QRST complex.

### ISSUE THREAD

**Issue by CosmoLuminous** [KIT-IBT/ECG_synthesization#1]
Hi @axel-loewe and @cnagel94,

I would like to understand how do you generate the p and qrst complexes exported in the files [p1_sim_unfiltered.mat](https://github.com/KIT-IBT/ECG-Synthesization/blob/main/example_signals/p1_sim_unfiltered.mat) and [p1_sim_unfiltered.mat](https://github.com/KIT-IBT/ECG-Synthesization/blob/main/example_signals/qrst1_sim_unfiltered.mat) respectively. Is there any paper which discuss about the generative model or a github repository for generating these samples?

If there is any existing material that discusses about the consolidated electrophysiological model of Heart for generating 12-lead which you have illustrated and discussed on a high level in your publication titled [MedalCare-XL: 16,900 healthy and pathological synthetic 12 lead ECGs from electrophysiological simulations](https://www.nature.com/articles/s41597-023-02416-4#Abs1), I request you to kindly provide me with the reference for the same. It would be quite helpful.

Thanks,
Aman

**Comment by axel-loewe** [comment]
Hi, 

the tool provided here has only one purpose: synthesizing multi-beat ECGs from input P waves and QRS complexes. 
For obtaining these building blocks, multiple methods can be used. What we have used in indeed described in the MedalCare-XL data publication [1] (methods section).
Some more technical details can be found in the methods comparison paper for P wave simulations [2] which also gives a number of pointers to publications regarding QRS complex simulations.
The openCARP simulator provides all functionality required for such simulations and some [tutorials](https://opencarp.org/documentation/examples/02_ep_tissue/07_extracellular) to get started with electrogram simulations: 

[1] Gillette, K., Gsell, M.A.F., Nagel, C. et al. MedalCare-XL: 16,900 healthy and pathological synthetic 12 lead ECGs from electrophysiological simulations. Sci Data 10, 531 (2023). [doi.org/10.1038/s41597-023-02416-4](https://doi.org/10.1038/s41597-023-02416-4)

[2] C. Nagel et al., "Comparison of Propagation Models and Forward Calculation Methods on Cellular, Tissue and Organ Scale Atrial Electrophysiology," in IEEE Transactions on Biomedical Engineering, vol. 70, no. 2, pp. 511-522, Feb. 2023, [doi: 10.1109/TBME.2022.3196144](https://doi.org/10.1109/TBME.2022.3196144)

**Comment by CosmoLuminous** [comment]
Thank you @axel-loewe for your prompt response. I will go through the second reference provided by you.

-Aman
